// Common Apple emoji for page icons, grouped like the macOS picker. Flags and rarely used glyphs are left out on purpose.
// Each entry is "emoji keywords…"; the keywords only feed the picker's filter.
const groups = {
  people: `😀 grin happy smile|😃 smile happy|😄 laugh happy|😁 grin beam|😆 laugh|😅 sweat relief|😂 joy tears laugh|🙂 slight smile|😉 wink|😊 blush happy|😇 angel halo|🥰 love hearts|😍 heart eyes love|🤩 star struck|😘 kiss|😋 yum tasty|😛 tongue|😜 wink tongue|🤪 zany crazy|😎 cool sunglasses|🤓 nerd glasses|🧐 monocle curious|🤔 thinking|🤨 raised eyebrow|😐 neutral|😑 expressionless|😶 no mouth|🙄 eye roll|😏 smirk|😬 grimace|😌 relieved|😔 pensive|😴 sleep tired|😷 mask sick|🤒 thermometer sick|🤯 mind blown|🥳 party celebrate|🥺 pleading|😢 cry sad|😭 sob|😤 triumph|😡 angry mad|🤬 swearing|😱 scream fear|😨 fearful|😰 anxious|🤗 hug|🤫 shush quiet|🤭 oops|😈 devil|👻 ghost|💀 skull|🤖 robot bot ai|👽 alien|💩 poop|👋 wave hello|🤚 raised hand|✋ hand stop|👌 ok|✌️ peace victory|🤞 fingers crossed luck|🤟 love you|👍 thumbs up yes|👎 thumbs down no|👏 clap|🙌 raise hands|🙏 pray thanks please|🤝 handshake deal|💪 muscle strong|✍️ writing hand|👀 eyes look|🧠 brain mind think|🫀 heart anatomy|👤 person user|👥 people team group|🧑‍💻 technologist developer coder|🧑‍🏫 teacher|🧑‍⚖️ judge law|🧑‍⚕️ doctor health|🧑‍🎓 student graduate|🧑‍🍳 cook chef|🧑‍🔬 scientist|🧑‍🎨 artist|🧑‍🚀 astronaut|🕵️ detective investigate|👨‍👩‍👧 family|🧘 yoga meditate|🏃 run|🚶 walk`,
  nature: `🐶 dog puppy|🐱 cat|🐭 mouse|🐰 rabbit bunny|🦊 fox|🐻 bear|🐼 panda|🐨 koala|🐯 tiger|🦁 lion|🐮 cow|🐷 pig|🐸 frog|🐵 monkey|🐔 chicken|🐧 penguin|🐦 bird|🦅 eagle|🦉 owl|🦋 butterfly|🐝 bee|🐞 ladybug|🐢 turtle|🐍 snake|🐙 octopus|🐬 dolphin|🐳 whale|🦈 shark|🐠 fish|🦄 unicorn|🐴 horse|🐘 elephant|🦒 giraffe|🦓 zebra|🐾 paw prints|🌵 cactus|🎄 tree christmas|🌲 evergreen tree|🌳 tree|🌴 palm tree|🌱 seedling grow sprout|🌿 herb leaf|☘️ shamrock|🍀 clover luck|🍁 maple leaf|🍂 fallen leaves autumn|🍃 leaves wind|🌷 tulip|🌹 rose|🌺 hibiscus|🌸 blossom cherry|🌼 flower|🌻 sunflower|🌞 sun face|🌝 moon face|🌙 moon night|⭐ star|🌟 glowing star|✨ sparkles magic|⚡ lightning zap|🔥 fire hot|🌈 rainbow|☀️ sun sunny|⛅ partly cloudy|☁️ cloud|🌧️ rain|⛈️ storm|❄️ snowflake cold|☃️ snowman|🌊 wave ocean water|💧 droplet water|🌍 earth globe world|🌎 globe americas|🌏 globe asia|🪐 planet saturn|☄️ comet`,
  food: `🍏 green apple|🍎 apple|🍐 pear|🍊 orange|🍋 lemon|🍌 banana|🍉 watermelon|🍇 grapes|🍓 strawberry|🫐 blueberries|🍒 cherries|🍑 peach|🥭 mango|🍍 pineapple|🥥 coconut|🥝 kiwi|🍅 tomato|🥑 avocado|🥦 broccoli|🥕 carrot|🌽 corn|🌶️ pepper hot|🥔 potato|🥐 croissant|🍞 bread|🧀 cheese|🥚 egg|🍳 cooking|🥞 pancakes|🥓 bacon|🍔 burger|🍟 fries|🍕 pizza|🌭 hot dog|🥪 sandwich|🌮 taco|🌯 burrito|🥗 salad|🍝 pasta|🍜 ramen noodles|🍣 sushi|🍱 bento|🍛 curry|🍚 rice|🥟 dumpling|🍤 shrimp|🍦 ice cream|🍩 donut|🍪 cookie|🎂 birthday cake|🍰 cake|🧁 cupcake|🍫 chocolate|🍬 candy|🍭 lollipop|🍯 honey|🥛 milk|☕ coffee|🍵 tea|🧃 juice|🥤 soda cup|🧋 bubble tea|🍺 beer|🍷 wine|🥂 cheers champagne|🍸 cocktail|🍽️ dinner plate|🧂 salt`,
  activity: `⚽ soccer football|🏀 basketball|🏈 football|⚾ baseball|🎾 tennis|🏐 volleyball|🏉 rugby|🎱 billiards|🏓 ping pong|🏸 badminton|⛳ golf|🏒 hockey|🥊 boxing|🥋 martial arts|🎿 ski|⛸️ skate|🏋️ weight lifting gym|🚴 cycling bike|🏊 swim|🧗 climbing|🏆 trophy win|🥇 gold medal first|🥈 silver medal|🥉 bronze medal|🏅 medal|🎖️ military medal|🎗️ ribbon|🎫 ticket|🎟️ tickets|🎪 circus|🎭 theater|🎨 art palette paint|🎬 film movie clapper|🎤 microphone sing|🎧 headphones music|🎼 score music|🎹 piano|🥁 drum|🎷 saxophone|🎺 trumpet|🎸 guitar|🎻 violin|🎲 dice game|♟️ chess|🎯 target goal bullseye|🎳 bowling|🎮 video game controller|🕹️ joystick|🧩 puzzle|🎉 party popper celebrate|🎊 confetti|🎈 balloon|🎁 gift present|🪄 magic wand`,
  travel: `🚗 car|🚕 taxi|🚌 bus|🏎️ race car|🚓 police car|🚑 ambulance|🚒 fire truck|🚚 truck delivery|🚜 tractor|🛵 scooter|🚲 bicycle|🚂 train|🚆 train|✈️ airplane flight travel|🛫 departure|🛬 arrival|🚀 rocket launch|🛸 ufo|🚁 helicopter|⛵ sailboat|🚤 speedboat|🚢 ship|⚓ anchor|🗺️ map|🧭 compass|🏔️ mountain snow|⛰️ mountain|🌋 volcano|🏕️ camping|🏖️ beach|🏝️ island|🏜️ desert|🏠 house home|🏡 home garden|🏢 office building|🏬 department store|🏦 bank|🏥 hospital|🏫 school|🏛️ classical building museum court|⛪ church|🕌 mosque|🏰 castle|🗽 statue of liberty|🗼 tower|🌉 bridge|🌃 night city|🏙️ cityscape|🎡 ferris wheel|🎢 roller coaster|⛲ fountain|⛺ tent|🚦 traffic light|🚧 construction|⛽ fuel gas|📍 pin location`,
  objects: `⌚ watch|📱 phone mobile|💻 laptop computer|⌨️ keyboard|🖥️ desktop computer|🖨️ printer|🖱️ mouse|💾 floppy save|💿 disc|📷 camera photo|📸 camera flash|📹 video camera|🎥 movie camera|📞 telephone|☎️ phone|📺 tv|📻 radio|🎙️ studio microphone podcast|⏰ alarm clock|⏳ hourglass|⌛ hourglass done|🕰️ clock|🔋 battery|🔌 plug|💡 light bulb idea|🔦 flashlight|🕯️ candle|🧯 extinguisher|💸 money wings|💵 dollar money cash|💰 money bag|💳 credit card|💎 gem diamond|⚖️ scales law justice balance|🧰 toolbox|🔧 wrench|🔨 hammer|⚒️ tools|🛠️ hammer wrench tools|⛏️ pick|🔩 bolt|⚙️ gear settings|🧱 brick|⛓️ chain|🧲 magnet|🔫 water gun|💣 bomb|🔪 knife|🛡️ shield|🔮 crystal ball|🧿 nazar|💈 barber|⚗️ alembic chemistry|🔭 telescope|🔬 microscope science|🩺 stethoscope doctor|💊 pill|💉 syringe|🧬 dna|🦠 microbe|🧪 test tube lab|🌡️ thermometer|🧹 broom|🧺 basket|🧻 paper|🚽 toilet|🛁 bathtub|🔑 key|🗝️ old key|🚪 door|🛋️ couch|🛏️ bed|🧸 teddy bear|🖼️ picture frame|🛍️ shopping bags|🛒 cart shopping|🎀 ribbon bow|✉️ envelope mail|📧 email|📨 incoming mail|📩 envelope arrow|📤 outbox|📥 inbox|📦 package box|🏷️ label tag|📪 mailbox|📮 postbox|📜 scroll|📃 page curl|📄 page document|📑 bookmark tabs|🧾 receipt|📊 bar chart|📈 chart up growth|📉 chart down|🗒️ notepad|🗓️ calendar spiral|📆 calendar tear|📅 calendar date|🗑️ trash wastebasket|📇 card index|🗃️ card file box|🗳️ ballot|🗄️ file cabinet|📋 clipboard|📁 folder|📂 open folder|🗂️ dividers|🗞️ newspaper|📰 news|📓 notebook|📔 notebook decorative|📒 ledger|📕 closed book red|📗 green book|📘 blue book|📙 orange book|📚 books library|📖 book open read|🔖 bookmark|🧷 safety pin|🔗 link|📎 paperclip attachment|🖇️ paperclips|📐 triangle ruler|📏 ruler|🧮 abacus|📌 pushpin|✂️ scissors|🖊️ pen|🖋️ fountain pen|✒️ nib pen|🖌️ paintbrush|🖍️ crayon|📝 memo note write|✏️ pencil edit|🔍 search magnifying|🔎 search right|🔏 lock pen|🔐 lock key|🔒 locked lock|🔓 unlocked|🎓 graduation cap|👑 crown|💼 briefcase work|🎒 backpack school|👓 glasses|🕶️ sunglasses|👔 tie|👕 shirt|👗 dress|👟 sneaker|👠 heel|💍 ring`,
  symbols: `❤️ red heart love|🧡 orange heart|💛 yellow heart|💚 green heart|💙 blue heart|💜 purple heart|🖤 black heart|🤍 white heart|🤎 brown heart|💔 broken heart|💕 two hearts|💖 sparkling heart|💯 hundred|💢 anger|💥 boom collision|💫 dizzy|💬 speech bubble chat|🗨️ speech left|🗯️ anger bubble|💭 thought bubble|💤 zzz sleep|✅ check done|☑️ checkbox|✔️ check mark|❌ cross no|❎ cross box|➕ plus add|➖ minus|➗ divide|✖️ multiply|❓ question|❔ white question|❗ exclamation|‼️ double exclamation|⚠️ warning|🚫 prohibited|⛔ no entry|🔞 no under 18|♻️ recycle|🔱 trident|⚜️ fleur|🔰 beginner|⭕ circle|🛑 stop sign|🔴 red circle|🟠 orange circle|🟡 yellow circle|🟢 green circle|🔵 blue circle|🟣 purple circle|⚫ black circle|⚪ white circle|🟥 red square|🟧 orange square|🟨 yellow square|🟩 green square|🟦 blue square|🟪 purple square|⬛ black square|⬜ white square|🔶 orange diamond|🔷 blue diamond|🔺 red triangle up|🔻 red triangle down|💠 diamond dot|🔘 radio button|🏁 checkered flag finish|🚩 red flag|🎌 crossed flags|🔔 bell notification|🔕 no bell|📣 megaphone|📢 loudspeaker announcement|🔊 speaker loud|🔇 mute|🎵 music note|🎶 notes music|⚛️ atom|☮️ peace|☯️ yin yang|♾️ infinity|🆕 new|🆗 ok button|🆒 cool|🆓 free|🆙 up|🔝 top|🔜 soon|🔙 back|🔛 on|🔚 end|ℹ️ information|🔤 abc|🔢 numbers 123|#️⃣ hash|*️⃣ asterisk|0️⃣ zero|1️⃣ one|2️⃣ two|3️⃣ three|4️⃣ four|5️⃣ five|6️⃣ six|7️⃣ seven|8️⃣ eight|9️⃣ nine|🔟 ten|▶️ play|⏸️ pause|⏹️ stop|⏺️ record|⏩ fast forward|⏪ rewind|🔀 shuffle|🔁 repeat|🔄 refresh sync|⬆️ up arrow|⬇️ down arrow|⬅️ left arrow|➡️ right arrow|↩️ return|↪️ forward|🔃 clockwise|💲 dollar sign|©️ copyright|®️ registered|™️ trademark`,
};

export type EmojiGroup = keyof typeof groups;
export interface EmojiEntry { emoji: string; keywords: string; group: EmojiGroup }

const groupOrder: readonly EmojiGroup[] = ['people', 'nature', 'food', 'activity', 'travel', 'objects', 'symbols'];

export const emojiGroups: readonly { group: EmojiGroup; entries: EmojiEntry[] }[] = groupOrder.map((group) => ({
  group,
  entries: groups[group].split('|').map((item) => {
    const space = item.indexOf(' ');
    return { emoji: item.slice(0, space), keywords: item.slice(space + 1), group };
  }),
}));
