import type { IconName } from '@/components/icon/icons';
export const folioSymbols = {
 'doc.text':'📄','doc.richtext':'📝','book':'📖','books.vertical':'📚','folder':'📁','folder.fill':'🗂️','tray.full':'📥','bookmark':'🔖','bookmark.fill':'🔖','star':'⭐','heart':'❤️','lightbulb':'💡','sparkles':'✨','sparkle':'✨','brain.head.profile':'🧠','bubble.left':'💬','bubble.left.and.bubble.right':'🗨️','quote.opening':'❝','pencil':'✏️','highlighter':'🖍️','paperclip':'📎','link':'🔗','calendar':'📅','calendar.day.timeline.left':'🗓️','clock':'🕒','checkmark.circle':'✅','checklist':'☑️','list.bullet':'☷','graduationcap':'🎓','briefcase':'💼','building.2':'🏢','house':'🏠','cross.case':'🩺','stethoscope':'🩺','scales':'⚖️','banknote':'💵','chart.bar':'📊','leaf':'🌿','globe.americas':'🌎','map':'🗺️','location':'📍','airplane':'✈️','car':'🚗','figure.run':'🏃','dumbbell':'🏋️','music.note':'🎵','camera':'📷','paintpalette':'🎨','wand.and.stars':'🪄','shippingbox':'📦','wrench.and.screwdriver':'🛠️','gearshape':'⚙️','lock':'🔒','key':'🔑','flag':'🚩','tag':'🏷️','archivebox':'🗃️','waveform':'🎙️','mic':'🎤','captions.bubble':'💬','video':'📹','person':'👤','person.2':'👥','graduationcap.fill':'🎓','house.fill':'🏠',
};


/** Stored in `note.icon` as `icon:<name>`; rendered as a grey monochrome glyph, like Notion's icon set. */
export const iconPrefix = 'icon:';
export type NoteIconGroup = 'documents' | 'work' | 'people' | 'creative' | 'science' | 'places' | 'life' | 'tech' | 'symbols';
export interface NoteIconOption { icon: IconName; group: NoteIconGroup }
// Object form keeps each name visible to the icon sprite generator (it scans `icon: '…'`).
export const noteIcons: readonly NoteIconOption[] = [
  { icon: 'file-text', group: 'documents' }, { icon: 'file', group: 'documents' }, { icon: 'file-list-2', group: 'documents' }, { icon: 'file-list-3', group: 'documents' }, { icon: 'sticky-note', group: 'documents' }, { icon: 'article', group: 'documents' }, { icon: 'draft', group: 'documents' }, { icon: 'newspaper', group: 'documents' }, { icon: 'book', group: 'documents' }, { icon: 'book-open', group: 'documents' }, { icon: 'book-marked', group: 'documents' }, { icon: 'booklet', group: 'documents' }, { icon: 'bookmark', group: 'documents' }, { icon: 'bookmark-3', group: 'documents' }, { icon: 'todo', group: 'documents' }, { icon: 'task', group: 'documents' }, { icon: 'list-check', group: 'documents' }, { icon: 'list-check-2', group: 'documents' }, { icon: 'checkbox-circle', group: 'documents' }, { icon: 'clipboard', group: 'documents' }, { icon: 'survey', group: 'documents' }, { icon: 'folder', group: 'documents' }, { icon: 'folder-3', group: 'documents' }, { icon: 'folders', group: 'documents' }, { icon: 'archive', group: 'documents' }, { icon: 'inbox', group: 'documents' }, { icon: 'attachment-2', group: 'documents' }, { icon: 'link', group: 'documents' },
  { icon: 'briefcase', group: 'work' }, { icon: 'building', group: 'work' }, { icon: 'building-2', group: 'work' }, { icon: 'bank', group: 'work' }, { icon: 'store', group: 'work' }, { icon: 'store-2', group: 'work' }, { icon: 'government', group: 'work' }, { icon: 'auction', group: 'work' }, { icon: 'scales-3', group: 'work' }, { icon: 'calendar', group: 'work' }, { icon: 'calendar-event', group: 'work' }, { icon: 'calendar-todo', group: 'work' }, { icon: 'time', group: 'work' }, { icon: 'alarm', group: 'work' }, { icon: 'timer', group: 'work' }, { icon: 'hourglass', group: 'work' }, { icon: 'bar-chart', group: 'work' }, { icon: 'bar-chart-2', group: 'work' }, { icon: 'pie-chart', group: 'work' }, { icon: 'line-chart', group: 'work' }, { icon: 'stock', group: 'work' }, { icon: 'money-dollar-circle', group: 'work' }, { icon: 'wallet', group: 'work' }, { icon: 'bank-card', group: 'work' }, { icon: 'coin', group: 'work' }, { icon: 'coins', group: 'work' }, { icon: 'price-tag-3', group: 'work' }, { icon: 'shopping-cart', group: 'work' }, { icon: 'shopping-bag', group: 'work' },
  { icon: 'user', group: 'people' }, { icon: 'user-3', group: 'people' }, { icon: 'team', group: 'people' }, { icon: 'group', group: 'people' }, { icon: 'parent', group: 'people' }, { icon: 'contacts', group: 'people' }, { icon: 'chat-1', group: 'people' }, { icon: 'chat-3', group: 'people' }, { icon: 'message', group: 'people' }, { icon: 'mail', group: 'people' }, { icon: 'send-plane', group: 'people' }, { icon: 'phone', group: 'people' }, { icon: 'mic', group: 'people' }, { icon: 'headphone', group: 'people' }, { icon: 'notification-3', group: 'people' }, { icon: 'emotion-happy', group: 'people' }, { icon: 'heart', group: 'people' }, { icon: 'star', group: 'people' }, { icon: 'award', group: 'people' }, { icon: 'medal', group: 'people' }, { icon: 'trophy', group: 'people' }, { icon: 'vip-crown', group: 'people' },
  { icon: 'pencil', group: 'creative' }, { icon: 'edit', group: 'creative' }, { icon: 'quill-pen', group: 'creative' }, { icon: 'pen-nib', group: 'creative' }, { icon: 'ink-bottle', group: 'creative' }, { icon: 'markup', group: 'creative' }, { icon: 'palette', group: 'creative' }, { icon: 'brush', group: 'creative' }, { icon: 'scissors', group: 'creative' }, { icon: 'ruler', group: 'creative' }, { icon: 'camera', group: 'creative' }, { icon: 'image', group: 'creative' }, { icon: 'video', group: 'creative' }, { icon: 'film', group: 'creative' }, { icon: 'movie', group: 'creative' }, { icon: 'music', group: 'creative' }, { icon: 'lightbulb', group: 'creative' }, { icon: 'magic', group: 'creative' }, { icon: 'sparkling', group: 'creative' }, { icon: 'puzzle', group: 'creative' }, { icon: 'gamepad', group: 'creative' },
  { icon: 'flask', group: 'science' }, { icon: 'test-tube', group: 'science' }, { icon: 'microscope', group: 'science' }, { icon: 'dna', group: 'science' }, { icon: 'heart-pulse', group: 'science' }, { icon: 'first-aid-kit', group: 'science' }, { icon: 'stethoscope', group: 'science' }, { icon: 'capsule', group: 'science' }, { icon: 'medicine-bottle', group: 'science' }, { icon: 'brain', group: 'science' }, { icon: 'pulse', group: 'science' }, { icon: 'fire', group: 'science' }, { icon: 'leaf', group: 'science' }, { icon: 'plant', group: 'science' }, { icon: 'seedling', group: 'science' }, { icon: 'tree', group: 'science' }, { icon: 'sun', group: 'science' }, { icon: 'moon', group: 'science' }, { icon: 'cloud', group: 'science' }, { icon: 'rainy', group: 'science' }, { icon: 'snowy', group: 'science' }, { icon: 'umbrella', group: 'science' },
  { icon: 'home', group: 'places' }, { icon: 'map', group: 'places' }, { icon: 'map-pin', group: 'places' }, { icon: 'compass-3', group: 'places' }, { icon: 'global', group: 'places' }, { icon: 'earth', group: 'places' }, { icon: 'plane', group: 'places' }, { icon: 'car', group: 'places' }, { icon: 'bus', group: 'places' }, { icon: 'train', group: 'places' }, { icon: 'ship', group: 'places' }, { icon: 'bike', group: 'places' }, { icon: 'rocket', group: 'places' }, { icon: 'run', group: 'places' }, { icon: 'walk', group: 'places' }, { icon: 'football', group: 'places' }, { icon: 'basketball', group: 'places' }, { icon: 'restaurant', group: 'places' }, { icon: 'cup', group: 'places' }, { icon: 'cake', group: 'places' }, { icon: 'goblet', group: 'places' }, { icon: 'gift', group: 'places' }, { icon: 'box-3', group: 'places' }, { icon: 'truck', group: 'places' },
  { icon: 'shield', group: 'life' }, { icon: 'shield-check', group: 'life' }, { icon: 'lock', group: 'life' }, { icon: 'key', group: 'life' }, { icon: 'fingerprint', group: 'life' }, { icon: 'eye', group: 'life' }, { icon: 'search', group: 'life' }, { icon: 'flag', group: 'life' }, { icon: 'target', group: 'life' }, { icon: 'focus', group: 'life' }, { icon: 'sword', group: 'life' }, { icon: 'hammer', group: 'life' }, { icon: 'tools', group: 'life' }, { icon: 'settings-3', group: 'life' },
  { icon: 'code', group: 'tech' }, { icon: 'code-box', group: 'tech' }, { icon: 'terminal-box', group: 'tech' }, { icon: 'database-2', group: 'tech' }, { icon: 'server', group: 'tech' }, { icon: 'cpu', group: 'tech' }, { icon: 'computer', group: 'tech' }, { icon: 'macbook', group: 'tech' }, { icon: 'smartphone', group: 'tech' }, { icon: 'robot', group: 'tech' }, { icon: 'robot-2', group: 'tech' }, { icon: 'ai-agent', group: 'tech' }, { icon: 'cloud-off', group: 'tech' }, { icon: 'bug', group: 'tech' }, { icon: 'git-branch', group: 'tech' }, { icon: 'github', group: 'tech' },
  { icon: 'check', group: 'symbols' }, { icon: 'close', group: 'symbols' }, { icon: 'add', group: 'symbols' }, { icon: 'question', group: 'symbols' }, { icon: 'information', group: 'symbols' }, { icon: 'alert', group: 'symbols' }, { icon: 'error-warning', group: 'symbols' }, { icon: 'arrow-right', group: 'symbols' }, { icon: 'arrow-up', group: 'symbols' }, { icon: 'loop-right-ai', group: 'symbols' }, { icon: 'stack', group: 'symbols' }, { icon: 'apps', group: 'symbols' }, { icon: 'pushpin', group: 'symbols' }, { icon: 'command', group: 'symbols' },
];
export const noteIconGroupOrder: readonly NoteIconGroup[] = ['documents', 'work', 'people', 'creative', 'science', 'places', 'life', 'tech', 'symbols'];
